### ISSUE TITLE
Feature: Change the sorting order of Java Heap by properties file.

### ISSUE THREAD

**Issue by ykubota** [HeapStats/HeapStatsFXAnalyzer#10]
The sorting order of Java Heap Graph at Summary Data of SnapShot Data is fixed.
To be more friendly, HeapStats should provide users the feature to change the sorting order by properties.

**Comment by ykubota** [comment]
@6a7561b

![graph](https://cloud.githubusercontent.com/assets/489607/9649599/2327d1b4-5232-11e5-8d8d-ae34f400fe71.png)

**Comment by ykubota** [comment]
Delete css and change a type of this option to boolean.

**Comment by YaSuenag** [comment]
Looks good!

**Comment by ykubota** [comment]
Thanks for your check. I will merge this branch with develop branch at first.
