### ISSUE TITLE
If heapstats_snapshot.dat has some uptimes, analyzer shows wrong results.

### ISSUE THREAD

**Issue by ykubota** [HeapStats/HeapStatsFXAnalyzer#12]
HeapStats agent stores the snapshot data without overwrite. So, if a user stops a JVM which agent is attached, the stored heapstats_snapshot.dat has some uptimes. 
However analyzer does not support the multiple uptimes. Thus analyzer views some wrong results, e.g., GC Count at Summary Data.

To view per uptimes, analyzer is better to show a user the time which a JVM had been restarted by line chart.

**Comment by ykubota** [comment]
Result:
![image](https://cloud.githubusercontent.com/assets/489607/9715447/1ae2086e-559b-11e5-98ca-1894be4601fa.png)

And this commit changes some color of graphs as below:
![image](https://cloud.githubusercontent.com/assets/489607/9715462/36525a86-559b-11e5-9ef1-2bf0faed6a97.png)
 * lime -> limegreen
 * yellow -> orange

**Comment by YaSuenag** [comment]
Which color is shown at Resource Data tab as reboot line?
I want you to use same color as reboot line between Resource Data and SnapShot Data.

**Comment by ykubota** [comment]
Nice catch :grin: 
![image](https://cloud.githubusercontent.com/assets/489607/9716345/a2977bba-55a3-11e5-9f28-e842d5ee4eb7.png)

**Comment by ykubota** [comment]
I catched other problem about SnapShot Data Pane which misdirect users. Please wait to resolve it.

![image](https://cloud.githubusercontent.com/assets/489607/9716554/c31bc934-55a5-11e5-9334-106e42921a8d.png)

**Comment by ykubota** [comment]
Latest results is as below:
![image](https://cloud.githubusercontent.com/assets/489607/9782570/2ab074c0-57d9-11e5-821b-cc430eb910d9.png)

**Comment by YaSuenag** [comment]
Good work!!
Please merge to develop branch.

**Comment by ykubota** [comment]
Merged. :sunny:
