### ISSUE TITLE
All table have needless space on right side

### ISSUE THREAD

**Issue by ykubota** [HeapStats/HeapStatsFXAnalyzer#14]
![image](https://cloud.githubusercontent.com/assets/489607/9805374/4a5ed560-5873-11e5-880d-6d2556546bc7.png)

**Comment by ykubota** [comment]
I use [TableView.CONSTRAINED_RESIZE_POLICY](http://docs.oracle.com/javase/8/javafx/api/javafx/scene/control/TableView.html#CONSTRAINED_RESIZE_POLICY) .

![image](https://cloud.githubusercontent.com/assets/489607/9805800/3e7f8a64-5878-11e5-816f-6fcf9f706cc0.png)

**Comment by YaSuenag** [comment]
I commented in your change: https://github.com/HeapStats/HeapStatsFXAnalyzer/commit/55aa70a87ebeda0a80adbb86f2926a7208a95397

**Comment by ykubota** [comment]
Thanks comment, I write a new commit.

**Comment by YaSuenag** [comment]
Thanks!
Looks good!!

**Comment by ykubota** [comment]
Merged into `develop`, closed.
