### ISSUE TITLE
Incomplete i18n at warning messages.

### ISSUE THREAD

**Issue by ykubota** [HeapStats/HeapStatsFXAnalyzer#15]
To set "language" property, an user can select "en" or "ja". But some warning messages shows only in English.

**Comment by ykubota** [comment]
Please check @6ac9d87f00d926e90e52c2647adaec6c0ef8dc50. :smiley:

**Comment by YaSuenag** [comment]
Looks good!!

**Comment by ykubota** [comment]
Thanks for your check, merge into `develop` by @4c2bdd48e733dcbf0efae63f6301a255a04f8e67.
