### ISSUE TITLE
Invalid properties errors are not shown at dialog

### ISSUE THREAD

**Issue by ykubota** [HeapStats/HeapStatsFXAnalyzer#16]
If an user run heapstats.jar by double-click without console, they can not see the invalid properties errors.

**Comment by ykubota** [comment]
![image](https://cloud.githubusercontent.com/assets/489607/9843784/74a12846-5af8-11e5-90b7-30d99922bd38.png)

**Comment by YaSuenag** [comment]
Looks good!

**Comment by ykubota** [comment]
Thanks for your check, merge into `develop` by @4c2bdd48e733dcbf0efae63f6301a255a04f8e67.
