### ISSUE TITLE
Add manual at "Help->How to use"

### ISSUE THREAD

**Issue by ykubota** [HeapStats/HeapStatsFXAnalyzer#18]
"Help -> How to use" on menu bar does not return any manual.
So, we should set new manual.

**Comment by ykubota** [comment]
@YaSuenag Please check the commit. :)

**Comment by YaSuenag** [comment]
Good work!
Please merge it to develop branch!

BTW, I think this issue is related to issue #9 .
I am certain this issue and #9 have been completed.
Can I announce that I will start to merge HeapStatsFXAnalyzer to IcedTea after merging rhis branch and closing all issues?

**Comment by ykubota** [comment]
Please announce :+1:

**Comment by ykubota** [comment]
Thanks check, I merged it to `develop`.
Please announce and start to merge. :+1:
