### ISSUE TITLE
We need sample plugin to learn the way to create plugins.

### ISSUE THREAD

**Issue by ykubota** [HeapStats/HeapStatsFXAnalyzer#7]
analyzer/contrib/RefTreePlugin will be move to builtin because this plugin provides the existing function of HeapStats analyzer. Thus, we should provide alternative sample plugin which can use as learning material.

**Comment by YaSuenag** [comment]
contribではなくplugin-sampleにして、Hello Worldレベルでいいかもしれません。
PostgreSQLだとcontribは拡張モジュールやツール類が入っているところなので、ディレクトリ名の意味が少し異なってくるかと。

**Comment by ykubota** [comment]
I have created HeapStats/SamplePlugin to provide a sample plugin.
Let's move to a new repository.
