### ISSUE TITLE
Add online manual to FXAnalyzer.

### ISSUE THREAD

**Issue by YaSuenag** [HeapStats/HeapStatsFXAnalyzer#9]
Current HeapStats Analyzer has online help as text file.
FXAnalyzer should have it too.

We have two approaches:

1. Add help file like current analyzer.
2. Add link to website (e.g. Online manual on HeapStats wiki)

I guess that we will create help contents on HeapStats wiki.
So we can set hyper link on "How to use" menu.

**Comment by ykubota** [comment]
We should migrate manual from current [help file(howtouse.txt)](http://icedtea.classpath.org/hg/heapstats/file/6b97debfe59d/analyzer/howtouse.txt)

At first, I write a manual at this wiki. Then when we release HeapStats 2.0, we will merge to the wiki. 

- Migrated chapter list
- [ ] Introduction
- [ ] Start HeapStats Analyzer
 - [ ] Log Collect Tab
 - [ ] Snapshot Tab
- [ ] Log Collect Tab
 - [ ] Resource Data Subtab
 - [ ] Log Detail Data Subtab
- [ ] Snapshot Tab
 - [ ] Summary Data Subtab
 - [ ] Delta Data Subtab
 - [ ] SnapShot Data Subtab
 - [ ] Reference Relationship Subtab
- [ ] Write to CSV
- [ ] Filter
 - [ ] Class Filter
 - [ ] Class Search
- [ ] Language
- [ ] Setting style of Class Path

**Comment by ykubota** [comment]
* WIP
 * https://github.com/HeapStats/HeapStatsFXAnalyzer/wiki/%5BWIP%5D-Online-manual

**Comment by YaSuenag** [comment]
Great work!

Can we add this link to HeapStatsFXAnalyzer?
If  so, we can merge HeapStatsFXAnalyzer to IcedTea and go to the next step.

**Comment by ykubota** [comment]
Yes. I will add the link when we completed.

**Comment by ykubota** [comment]
* Complete
 * https://github.com/HeapStats/HeapStatsFXAnalyzer/wiki/%5BWIP%5D-Online-manual

I will move this wiki to icedtea.

**Comment by ykubota** [comment]
Moved to below, temporally.
 * http://icedtea.classpath.org/wiki/HeapStats/HeapStatsFXAnalyzer

Is this acceptable? Otherwise, we should move to below?
 * http://icedtea.classpath.org/wiki/HeapStats/Analyzer

**Comment by YaSuenag** [comment]
Thank you so much!
Nice work!!

I think we can move current analyzer contents to "HeapStats/Analyzer-1.x", and FXAnalyzer can be located to "HeapStats/Analyzer-2.x" .
What do you thinkl?

**Comment by ykubota** [comment]
:+1:

Any objections are not until this reply, so I will move those pages.

**Comment by ykubota** [comment]
* Old page: http://icedtea.classpath.org/wiki/HeapStats/Analyzer
* For version 1.x: http://icedtea.classpath.org/wiki/HeapStats/Analyzer-version1
* For version 2.x: http://icedtea.classpath.org/wiki/HeapStats/Analyzer-version2

**Comment by ykubota** [comment]
Enjoy :)
